/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SNS API
 * This is a simple SNS API server
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ModelsComment
} from '../../types/api';




  export const getComments = () => {
/**
 * Post a comment on an article
 * @summary Create a new comment
 */
const postComment = <TData = AxiosResponse<ModelsComment>>(
    modelsComment: ModelsComment, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/comment`,
      modelsComment,options
    );
  }
return {postComment}};
export type PostCommentResult = AxiosResponse<ModelsComment>
