/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SNS API
 * This is a simple SNS API server
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getHello = () => {
/**
 * Returns hello world message
 * @summary Hello World
 */
const getHello = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/hello`,{
        responseType: 'text',
    ...options,}
    );
  }
return {getHello}};
export type GetHelloResult = AxiosResponse<string>
