/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SNS API
 * This is a simple SNS API server
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ControllersLoginRequest,
  ControllersLoginResponse
} from '../../types/api';




  export const getAuth = () => {
/**
 * Validate Google ID token and set HttpOnly cookie
 * @summary Google OAuth Login
 */
const postAuthLogin = <TData = AxiosResponse<ControllersLoginResponse>>(
    controllersLoginRequest: ControllersLoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/login`,
      controllersLoginRequest,options
    );
  }
/**
 * Clear authentication cookie
 * @summary Logout
 */
const postAuthLogout = <TData = AxiosResponse<void>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/auth/logout`,undefined,options
    );
  }
return {postAuthLogin,postAuthLogout}};
export type PostAuthLoginResult = AxiosResponse<ControllersLoginResponse>
export type PostAuthLogoutResult = AxiosResponse<void>
