/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SNS API
 * This is a simple SNS API server
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetArticleListParams,
  ModelsArticle
} from '../../types/api';




  export const getArticles = () => {
/**
 * Post a new article
 * @summary Create a new article
 */
const postArticle = <TData = AxiosResponse<ModelsArticle>>(
    modelsArticle: ModelsArticle, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/article`,
      modelsArticle,options
    );
  }
/**
 * Get a single article with its comments
 * @summary Get article by ID
 */
const getArticleId = <TData = AxiosResponse<ModelsArticle>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/article/${id}`,options
    );
  }
/**
 * Get paginated article list
 * @summary Get article list
 */
const getArticleList = <TData = AxiosResponse<ModelsArticle[]>>(
    params?: GetArticleListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/article/list`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
/**
 * Increment the nice counter for an article
 * @summary Add a nice (like) to article
 */
const postArticleNice = <TData = AxiosResponse<ModelsArticle>>(
    modelsArticle: ModelsArticle, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/article/nice`,
      modelsArticle,options
    );
  }
return {postArticle,getArticleId,getArticleList,postArticleNice}};
export type PostArticleResult = AxiosResponse<ModelsArticle>
export type GetArticleIdResult = AxiosResponse<ModelsArticle>
export type GetArticleListResult = AxiosResponse<ModelsArticle[]>
export type PostArticleNiceResult = AxiosResponse<ModelsArticle>
