/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SNS API
 * This is a simple SNS API server
 * OpenAPI spec version: 1.0
 */

export type GetArticleListParams = {
/**
 * Page number
 */
page?: number;
};
