/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SNS API
 * This is a simple SNS API server
 * OpenAPI spec version: 1.0
 */
import type { ModelsComment } from './modelsComment';

export interface ModelsArticle {
  article_id?: number;
  comments?: ModelsComment[];
  contents?: string;
  created_at?: string;
  nice?: number;
  title?: string;
  user_name?: string;
}
