/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * SNS API
 * This is a simple SNS API server
 * OpenAPI spec version: 1.0
 */

export interface ModelsComment {
  article_id?: number;
  comment_id?: number;
  created_at?: string;
  message?: string;
}
